BlockchaneContract/ViewModels/HomeViewModel.cs
using BlockchaneContract.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;

namespace BlockchaneContract.ViewModels
{
    public class HomeViewModel
    {
        public List<ContractBlock> Contracts { get; set; }
        public List<Block> BlockChain{ get; set; }
        public List<Node> Nodes { get; set; }
        public ContractBlock Contract { get; set; }
        public string Signature { get; set; }
        public string Title { get; set; }
        public string Password { get; set; }
        public bool Verified { get; set; }
        public string Key { get; set; }
        public Bitmap QrCodeImage { get; set; }
    }
}

BlockchaneContract/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlockchaneContract.ViewModels
{
    public class LoginViewModel
    {
        //[Required]
        //[Display(Name = "User name")]
        //public string UserName { get; set; }

        //[DataType(DataType.Password)]
        //public string Password { get; set; }


        //[DataType(DataType.EmailAddress)]
        //public string EmailAddress { get; set; }
    }
}

BlockchaneContract/ViewModels/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BlockchaneContract.ViewModels
{
    public class RegisterViewModel
    {
        //[Required]
        //[Display(Name = "User name")]
        //public string UserName { get; set; }

        //[Required]
        //[DataType(DataType.Password)]
        //public string Password { get; set; }

        //   [Required]
        //[DataType(DataType.EmailAddress)]
        //public string EmailAddress { get; set; }

        //[Required]
        //public String Key { get; set; }

    }
}

BlockchaneContract/Controllers/HomeController.cs
using System.IO;
using System.Linq;
using BlockchaneContract.Models;
using BlockchaneContract.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace BlockchaneContract.Controllers
{
   // [Authorize]
  //[ Route("api/[controller]")]
    public class HomeController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IContractRepository _ContractRepository;
        public HomeController(AppDbContext context, IContractRepository contractRepository)
        {
            _context = context;
            _ContractRepository = contractRepository;
        }
        public IActionResult Register()
        {
            return RedirectToAction("Register", "Account");
        }
        [Authorize]
        public IActionResult Contracts()
        {
            var contracts = _ContractRepository.GetAllContracts().OrderByDescending(c => c.Date);
            var homeViewModel = new HomeViewModel()
            {
                Title = "Pending contracts:  ",
                Contracts = contracts.ToList(),
                //QrCodeImage = qrCodeImage
            };
            return View(homeViewModel);
                        
                   }






        
        [HttpGet("api/home/ContractsApi")]
        public IActionResult ContractsApi()
        {
            var contracts = _ContractRepository.GetAllContracts().OrderByDescending(c => c.Date);

            return new JsonResult(contracts);

        }








       // [HttpGet("api/home/PendingContracts")]
        public IActionResult PendingContracts()
        {
            var pending = _ContractRepository.GetPendingContracts();
            //var homeViewModel = new HomeViewModel()
            //{
            //    Contracts = pending.ToList()
            //};

            return new JsonResult(pending);
        }
        

        [HttpGet("api/home/contractdetails/{id}")]
        public IActionResult ContractDetails(int id)
        {
            var contract = _ContractRepository.GetContractById(id);
            var homeViewModel = new HomeViewModel()
            {
                Contract = contract
            };
            return View(homeViewModel);
        }

        public IActionResult Queue()
        {
            var queue = _ContractRepository.GetQueue();
            var homeViewModel = new HomeViewModel()
            {
                Contracts = queue.ToList()
            };

            return View(homeViewModel);
        }


        public IActionResult ReceivedBlocks()
        {
            return View();
        }


        public IActionResult Identity()
        {
            return View();
        }


        public IActionResult ImportContract()
        {

            ContractBlock contract = JsonConvert.DeserializeObject<ContractBlock>(System.IO.File.ReadAllText("C:/Users/Fatma/Desktop/Contract.json"));
            _context.Add(contract);
           // _context.SaveChanges();

            HomeViewModel homeViewModel = new HomeViewModel { Contract = contract };
            return View(homeViewModel);
        }

    }
}

BlockchaneContract/Controllers/NodesController.cs
using BlockchaneContract.Models;
using BlockchaneContract.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace BlockchaneContract.Controllers
{

    public class NodesController : Controller
    {
        private readonly IBlockRepository _blockChainRepository;
        private readonly IContractRepository _contractRepository;
        public NodesController(IBlockRepository blockChainRepository, IContractRepository contractRepository)
        {
            _blockChainRepository = blockChainRepository;
            _contractRepository = contractRepository;
        }

        // GET: /<controller>/



        // GET: /<controller>/
        public IActionResult Status()
        {
            return View();
        }

        public IActionResult BlockChainDetails(Guid id)
        {
            Block block= _blockChainRepository.GetBlockChainById(id);
            if (block == null)
                return NotFound();
            block.Contracts = _contractRepository.GetContractsByBlock(id).ToList();
            return View(block);
        }



        public IActionResult BlockChainContracts(Guid id)
        {
            var contracts = _contractRepository.GetContractsByBlock(id);
            if (contracts == null)
                return NotFound();

            var homeViewModel = new HomeViewModel()
            {
                Title = contracts.Count().ToString(),
                Contracts = contracts.ToList()
            };

            return View(homeViewModel);

        }



        public IActionResult Blockchain()
        {
            var blockChain = _blockChainRepository.GetBlockChain().OrderBy(c => c.Date);
            var pending = _contractRepository.GetPendingContracts();
            var homeViewModel = new HomeViewModel()

            {
                Title = "BlockChain  ",
                BlockChain = blockChain.ToList(),
                Contracts=pending.ToList()
                
            };

            return View(homeViewModel);
        }

    }
}

BlockchaneContract/Views/Home/ContractDetails.cshtml
@model HomeViewModel
@using System.IO

<section class="content-header ">
    <h1>
        Contract
        <small> Contract details</small>
        <br />
    </h1>

    <ol class="breadcrumb">
        <li><a href="@Url.Action("", "")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="@Url.Action("Contracts", "Home")">Contracts</a></li>
        <li class="active">Contract details</li>
    </ol>
</section><br />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<div class="btn btn-brimary pull-right">
    <div class=" btn btn-default FontSmaller fa fa-download"> <a href="#" onclick="HTMLtoPDF()">   Download as PDF</a></div>

</div>
<div id="HTMLtoPDF">


    <div>
        <div class="col-md-pull-6 pln">
            <h3 class="upper mb-25 center-tablet mt-40"> <small> <small>Contract Id</small>   @Model.Contract.Id </small> </h3>
            <table class="table table-striped">
                <tr>
                    <td width="50%">Id Block</td>
                    <td colspan="2">@Model.Contract.IdBlock </td>
                </tr>
                <tr>
                    <td>Date</td>
                    <td colspan="2">@Model.Contract.Date </td>
                </tr>
                <tr>
                    <td>Version</td>
                    <td colspan="2">@Model.Contract.Version</td>
                </tr>

                <tr>
                    <td>Nym</td>
                    <td colspan="2">@Model.Contract.Nym</td>
                </tr>

                <tr>
                    <td>Signature   </td>
                    <td> @*<a data-toggle="collapse" data-target="#demo">*@@Model.Contract.Signature</td>
                    @*<div id="demo" class="collapse">@Model.Contract.Signature</div>*@

                </tr>

            </table>
        </div>
    </div>

    <br />

    <div class="col-md-pull-6 pln">
        <div class="col-md-pull-6 pln">
            <table class="table table-striped">
                <tr class="upper mb-25 center-tablet mt-40">
                    <td>
                        <strong>  Body:</strong><br /><br />
                        <small>  @Model.Contract.ContractBody</small>
                    </td>
                </tr>
            </table>
        </div>

    </div>

</div>

@if (@Model.Contract.Signature.Length == 0)
{
<div class="row">
    <div class="col-xs-12">
        <button class="btn btn-primary btn-sm pull-right" data-target="#loginModal" data-toggle="modal">Sign  </button>
        <div class="modal fade" tabindex="-1" id="loginModal"
             data-keyboard="false" data-backdrop="static">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            &times;
                        </button>
                        <h4 class="modal-title">Confirm the password to sign: </h4>
                    </div>
                    <div class="modal-body">
                        <form id="loginModal" method="post" name="loginModal" asp-route-id=password asp-action="ImportKey" asp-controller="Sign">
                            <div class="form-group">
                                <label>Password</label>
                                <input asp-for="Password" class="form-control" placeholder="password" type="password" id="password" name="password" />
                            </div>
                            <input type="submit" class="btn btn-primary" value="Login  " id="idLog">
                            <button type="button" class="btn btn-primary " data-dismiss="modal"> Cancel</button>
                        </form>
                        <div id="res"></div>
                    </div>
                    <div class="modal-footer">

                    </div>
                </div>
            </div>
        </div>
        <a href="@Url.Action("Contracts", "Home" )"> <i class="glyphicon glyphicon-circle-arrow-left pull"></i> Retour</a>

    </div>

</div>}
else
{
    <i class="btn btn-success btn-sm pull-right">Signed   </i>
    <a href="@Url.Action("Contracts", "Home" )"> <i class="glyphicon glyphicon-circle-arrow-left pull"></i> Retour</a>

}  <br />

<div class="pull-right">
    <br />
</div>
<script src="~/js/jspdf.js"></script>
<script src="~/js/jquery-2.1.3.js"></script>
<script src="~/js/pdfFromHTML.js"></script>

BlockchaneContract/Views/Home/Contracts.cshtml
@model HomeViewModel
@using Microsoft.AspNetCore.Authentication;

<section class="content-header ">
    <h1>
        Home <small> All Contracts</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action("", "")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Contracts</li>
    </ol>
</section><br />


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">



<div class="btn btn-brimary pull-right">
    <div class="  col-xs-12">
        <div class=" btn btn-default FontSmaller fa fa-download"> <a href="#" onclick="HTMLtoPDF()">   Download as PDF</a></div>
        <div class="btn btn-default FontSmaller fa fa-upload"> <a asp-controller="Home" asp-action="ImportContract">   Upload contracts </a></div>
        <br />   <br />
    </div>
</div>
<div id="HTMLtoPDF">

    <input class="form-control" id="myInput" type="text" placeholder="Search.."><br />

    <table id="id" class="table table-striped table-hover table-responsive">
        <thead>
            <tr style="text-decoration-color:grey">
                <td><small>contract Id <i class="pull-right" onclick="sortTable()"><i class="fa fa-sort-numeric-asc"></i></i></small></td>
                <td><small>BlockId <i></i></small></td>
                <td><small>Version </small></td>

                <td>
                    <small>
                        Date
                    </small>
                </td>
                <th><small> </small></th>
                <th><small>  </small></th>
            </tr>
        </thead>
        <tbody id="myTable">
            @foreach (var contract in @Model.Contracts)
            {
                <tr>

                    <td> <a asp-controller="Home" asp-action="ContractDetails" asp-route-id="@contract.Id" class="FontSmaller"><strong>#@contract.Id</strong></a> </td>
                    <td><a asp-controller="Nodes" asp-action="BlockChainDetails" asp-route-id="@contract.IdBlock" class="FontSmaller"><small>@contract.IdBlock</small></a></td>
                    <td><i><small> @contract.Version</small></i></td>

                    <td><i><small> @contract.Date</small></i></td>
                    <td> <a asp-controller="Home" asp-action="ContractDetails" asp-route-id="@contract.Id"><i><small>More >></small></i></a> </td>

                    <td>
                        @{ if (contract.Signature.Length == 0)
                            {
                                <div class="row">
                                    <div class="col-xs-12">
                                        <button class="btn btn-primary btn-sm pull-right" data-target="#loginModal" data-toggle="modal">Sign  </button>
                                        <div class="modal fade" tabindex="-1" id="loginModal"
                                             data-keyboard="false" data-backdrop="static">
                                            <div class="modal-dialog modal-sm">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal">
                                                            &times;
                                                        </button>
                                                        <h4 class="modal-title">Confirm the password to sign: </h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <form id="loginModal" method="post" name="loginModal" asp-route-id=password asp-action="ImportKey" asp-controller="Sign">

                                                            <div class="form-group">
                                                                <label>Password</label>
                                                                <input asp-for="Password" class="form-control" placeholder="password" type="password" id="password" name="password" />
                                                            </div>                                                    <input type="submit" class="btn btn-primary" value="Login  " id="idLog">
                                                            <button type="button" class="btn btn-primary " data-dismiss="modal">
                                                                Cancel
                                                            </button>
                                                        </form>
                                                        <div id="res"></div>
                                                    </div>
                                                    <div class="modal-footer">

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>}
                            else
                            {
                                <i class="btn btn-success btn-sm pull-right">Signed   </i>

                            }


                        }
                    </td>
                    @*<th> <a asp-controller="Sign" asp-action="Index" asp-route-id="@contract.Id"><small>testSign</small></a></th>*@

                    <td> <a asp-controller="Sign" asp-action="Index" asp-route-id="@contract.Id"><small>testSign</small></a></td>

                </tr>
            }
        </tbody>



        <script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
        </script>
    </table>
</div>


<script src="../../bower_components/jquery/dist/jquery.min.js"></script>
<script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="../../bower_components/datatables.net/js/jquery.dataTables.min.js"></script>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

BlockchaneContract/Views/Home/ExportPdf.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

BlockchaneContract/Views/Home/HashBlock.cshtml
@model HashViewModel
hash= @Model.BlockChain.Hash <br />

prevHash=  @Model.BlockChain.PreviousHash <br />

public key: @Model.PublicKey <br />

BlockchaneContract/Views/Home/ImportContract.cshtml
@model HomeViewModel
@using System.IO

<section class="content-header ">
    <h1>
        Contract
        <small>Import contract</small>
        <br />
    </h1>

    <ol class="breadcrumb">
        <li><a href="@Url.Action("", "")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="@Url.Action("Contracts", "Home")">Contracts</a></li>
        <li class="active">Import contract</li>
    </ol>
</section><br />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<div class="btn btn-brimary pull-right">
    <div class=" fa fa-download col-xs-12">
        <a href="#" onclick="HTMLtoPDF()">Download as PDF</a>

    </div>
</div>
<div id="HTMLtoPDF">
    <div>
        <div class="col-md-pull-6 pln">
            <table class="table table-striped">
               
                <tr>
                    <td>Date</td>
                    <td colspan="2">@Model.Contract.Date </td>
                </tr>
                <tr>
                    <td>Version</td>
                    <td colspan="2">@Model.Contract.Version</td>
                </tr>

                <tr>
                    <td>Nym</td>
                    <td colspan="2">@Model.Contract.Nym</td>
                </tr>

            </table>
        </div>
    </div>

    <br />

    <div class="col-md-pull-6 pln">
        <div class="col-md-pull-6 pln">
            <table class="table table-striped">
                <tr class="upper mb-25 center-tablet mt-40">
                    <td>
                        <strong>  Body:</strong><br /><br />
                        <small>  @Model.Contract.ContractBody</small>
                    </td>
                </tr>
            </table>
        </div>

    </div>

</div>



<div class="pull-right">
    <br />
</div>
<script src="~/js/jspdf.js"></script>
<script src="~/js/jquery-2.1.3.js"></script>
<script src="~/js/pdfFromHTML.js"></script>

BlockchaneContract/Views/Home/Login.cshtml
@model BlockchaneContract.ViewModels.LoginViewModel
<!-- jQuery 3 -->
<script src="../../bower_components/jquery/dist/jquery.min.js"></script>
<!-- Bootstrap 3.3.7 -->
<script src="../../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<!-- iCheck -->
<script src="../../plugins/iCheck/icheck.min.js"></script>


<script>
    $(function () {
        $('input').iCheck({
            checkboxClass: 'icheckbox_square-blue',
            radioClass: 'iradio_square-blue',
            increaseArea: '20%' /* optional */
        });
    });
</script>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

<form asp-action="Login" asp-controller="Account" method="post" class="form-horizontal" role="form">

    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="UserName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Log in" />
        </div>
    </div>
</form>

<form asp-action="Register" asp-controller="Home" method="post" class="form-horizontal" role="form">
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Log in" />
        </div>
    </div>

</form>

BlockchaneContract/Views/Home/LoginIdentity.cshtml
@{
    ViewData["Title"] = "Identity";
}

<h2>Identity</h2>

BlockchaneContract/Views/Home/PendingContracts.cshtml
@model HomeViewModel
<section class="content-header ">
    <h1>
        Node <small> Pending contracts</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action(" ", " ")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="@Url.Action("Status", "Node")"> Node</a></li>
        <li class="active">Pending contracts</li>
    </ol>
</section>

<div class="btn btn-brimary pull-right">

        <div class=" btn btn-default FontSmaller fa fa-download"> <a href="#" onclick="HTMLtoPDF()">   Download as PDF</a></div>

    
</div><div style="width:100%;      clear:both;">
    <br />
    <table id="HTMLtoPDF" style="width:100%; clear:both;" class="table table-striped table-hover table-responsive">
        <thead>
            <tr style="text-decoration-color:grey">
                <dialog>hello</dialog>
                <th><small>contract Id</small></th>
                <th><small>Date</small> </th>
                <th><small> Type</small></th>
                <th><small>Version </small></th>
                <th><small>  </small></th>
            </tr>
        </thead>
        @foreach (var contract in Model.Contracts)
        {
        <tr>
            <th> <a asp-controller="Home" asp-action="ContractDetails" asp-route-id="@contract.Id">#@contract.Id</a> </th>
            <th><i><small> @contract.Date</small></i></th>
            <th><i><small> @contract.Type</small></i></th>
            <th><i><small> @contract.Version</small></i></th>
            <th> <a asp-controller="Home" asp-action="ContractDetails" asp-route-id="@contract.Id"><i><small><small>More >></small></small></i></a> </th>

            <th>
                @{ if (contract.Signature.Length == 0)
            {
                <div class="row">
                    <div class="col-xs-12">
                        <button class="btn btn-primary btn-sm pull-right" data-target="#loginModal" data-toggle="modal">Sign  </button>
                        <div class="modal fade" tabindex="-1" id="loginModal"
                             data-keyboard="false" data-backdrop="static">
                            <div class="modal-dialog modal-sm">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">
                                            &times;
                                        </button>
                                        <h4 class="modal-title">Confirm the password to sign: </h4>
                                    </div>
                                    <div class="modal-body">
                                        <form id="loginModal" method="post" name="loginModal" asp-route-id=password asp-action="ImportKey" asp-controller="Sign">

                                            <div class="form-group">
                                                <label>Password</label>
                                                <input asp-for="Password" class="form-control" placeholder="password" type="password" id="password" name="password" />
                                            </div>                                                    <input type="submit" class="btn btn-primary" value="Login  " id="idLog">
                                            <button type="button" class="btn btn-primary " data-dismiss="modal">
                                                Cancel
                                            </button>
                                        </form>
                                        <div id="res"></div>
                                    </div>
                                    <div class="modal-footer">

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>}
    else
    {
        <i class="btn btn-success btn-sm pull-right">Signed   </i>

}


                }
            </th>
            @*<th> <a asp-controller="Sign" asp-action="Index" asp-route-id="@contract.Id"><small>testSign</small></a></th>*@
        </tr>
        }
        <thead>
    </table>
</div>

BlockchaneContract/Views/Home/Queue.cshtml
@model HomeViewModel
<section class="content-header ">
    <h1>
        Queue
    </h1>
    <ol class="breadcrumb">
        <li><a href="@Url.Action(" ", " ")"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Queue</li>
    </ol>
</section>

<div class="btn btn-brimary pull-right">
    <div class=" fa fa-file-pdf col-xs-12">
        <div class=" btn btn-default FontSmaller fa fa-download"> <a href="#" onclick="HTMLtoPDF()">   Download as PDF</a></div>

    </div>
</div>

<div id="HTMLtoPDF" style="width:100%;      clear:both;">
    <br />

    <table id="HTMLtoPDF" style="width:100%; clear:both;" class="table table-striped table-hover table-responsive">
        <thead>
            <tr style="text-decoration-color:grey">
                <dialog>hello</dialog>
                <th><small>contract Id</small></th>
                <th><small>Date</small> </th>
                <th><small> Type</small></th>
                <th><small>Version </small></th>
                <th><small>  </small></th>
            </tr>
        </thead>
        @foreach (var contract in Model.Contracts)
        {
            <tr>
                <th> <a asp-controller="Home" asp-action="ContractDetails" asp-route-id="@contract.Id">#@contract.Id</a> </th>
                <th><i><small> @contract.Date</small></i></th>
                <th><i><small> @contract.Type</small></i></th>
                <th><i><small> @contract.Version</small></i></th>
                <th> <a asp-controller="Home" asp-action="ContractDetails" asp-route-id="@contract.Id"><i><small><small>More >></small></small></i></a> </th>

            </tr>
        }

    </table>
</div>
<div class=" btn btn-block btn-lg  fa fa-hashtag pull-right">
    <a asp-controller="Sign" asp-action="HashBlock" asp-route-id="@Model.Contracts">Create the new block's hash </a>
</div>

BlockchaneContract/Views/Home/ReceivedBlocks.cshtml
<div class="btn btn-brimary pull-right">
    <div class=" fa fa-file-pdf col-xs-12">
        <a href="#" onclick="HTMLtoPDF()">Download as PDF</a>

    </div>
</div>


<div id="HTMLtoPDF"></div>

BlockchaneContract/Views/Home/Register.cshtml
@model LoginViewModel

<form asp-action="Register" asp-controller="Account" method="post" class="form-horizontal" role="form">

    <div asp-validation-summary="All" class="text-danger"></div>


    <div class="form-group">
        <label asp-for="UserName" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="UserName" class="form-control" />
            <span asp-validation-for="UserName" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-primary" value="Register" />
        </div>
    </div>
</form>